/*
 * Simple Students API
 * A simple API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * InlineResponse200
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-07-31T19:56:25.102Z[GMT]")
public class InlineResponse200 {
  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("studentsList")
  private List<Object> studentsList = null;

  public InlineResponse200 groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @Schema(description = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public InlineResponse200 studentsList(List<Object> studentsList) {
    this.studentsList = studentsList;
    return this;
  }

  public InlineResponse200 addStudentsListItem(Object studentsListItem) {
    if (this.studentsList == null) {
      this.studentsList = new ArrayList<Object>();
    }
    this.studentsList.add(studentsListItem);
    return this;
  }

   /**
   * Get studentsList
   * @return studentsList
  **/
  @Schema(description = "")
  public List<Object> getStudentsList() {
    return studentsList;
  }

  public void setStudentsList(List<Object> studentsList) {
    this.studentsList = studentsList;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse200 inlineResponse200 = (InlineResponse200) o;
    return Objects.equals(this.groupName, inlineResponse200.groupName) &&
        Objects.equals(this.studentsList, inlineResponse200.studentsList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, studentsList);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse200 {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    studentsList: ").append(toIndentedString(studentsList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
